/* DROP
DROP TABLE TRN_SHUSHI_DTL
;
DROP TABLE TRN_SHUSHI
;
DROP TABLE MST_KOJIN
;
DROP TABLE MST_SETAI
;
DROP TABLE MST_HIMOKU
;
DROP TABLE MST_CODE
;
DROP TABLE MST_CODE_CLASS
;
*/
--------------------------------------------------------------------------------
-- Table : MST_CODE_CLASS
CREATE TABLE MST_CODE_CLASS(
	CLASS_CODE VARCHAR2(3) NOT NULL ENABLE
	, CLASS_NM VARCHAR2(100)
	, DEL_FLG VARCHAR2(1)
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1
	, CONSTRAINT MST_CODE_CLASS_PK PRIMARY KEY (CLASS_CODE)
);

COMMENT
	ON TABLE MST_CODE_CLASS IS 'コード分類マスタ';

COMMENT
	ON COLUMN MST_CODE_CLASS.CLASS_CODE IS '分類コード';

COMMENT
	ON COLUMN MST_CODE_CLASS.CLASS_NM IS '分類名称';

COMMENT
	ON COLUMN MST_CODE_CLASS.DEL_FLG IS '削除フラグ';

COMMENT
	ON COLUMN MST_CODE_CLASS.INS_USER IS '登録者';

COMMENT
	ON COLUMN MST_CODE_CLASS.INS_DATE IS '登録日';

COMMENT
	ON COLUMN MST_CODE_CLASS.UPD_USER IS '更新者';

COMMENT
	ON COLUMN MST_CODE_CLASS.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN MST_CODE_CLASS.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : MST_CODE
CREATE TABLE MST_CODE(
	CLASS_CODE VARCHAR2(3) NOT NULL
	, CD VARCHAR2(3) NOT NULL
	, CD_NM VARCHAR2(100)
	, DEL_FLG VARCHAR2(1)
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1
	, CONSTRAINT MST_CODE_PK PRIMARY KEY (CLASS_CODE, CD)
);

COMMENT
	ON TABLE MST_CODE IS 'コードマスタ';

COMMENT
	ON COLUMN MST_CODE.CLASS_CODE IS '分類コード';

COMMENT
	ON COLUMN MST_CODE.CD IS 'コード';

COMMENT
	ON COLUMN MST_CODE.CD_NM IS 'コード名称';

COMMENT
	ON COLUMN MST_CODE.DEL_FLG IS '削除フラグ';

COMMENT
	ON COLUMN MST_CODE.INS_USER IS '登録者';

COMMENT
	ON COLUMN MST_CODE.INS_DATE IS '登録日';

COMMENT
	ON COLUMN MST_CODE.UPD_USER IS '更新者';

COMMENT
	ON COLUMN MST_CODE.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN MST_CODE.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : MST_HIMOKU
CREATE TABLE MST_HIMOKU(
	HIMOKU_CD VARCHAR2(2) NOT NULL ENABLE
	, HIMOKU_NM NVARCHAR2(32) NOT NULL ENABLE
	, HIMOKU_KBN VARCHAR2(1) NOT NULL ENABLE
	, DEL_FLG VARCHAR2(1)
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1 NOT NULL ENABLE
	, CONSTRAINT MST_HIMOKU_PK PRIMARY KEY (HIMOKU_CD)
);

COMMENT
	ON TABLE MST_HIMOKU IS '費目マスタ';

COMMENT
	ON COLUMN MST_HIMOKU.HIMOKU_CD IS '費目CD';

COMMENT
	ON COLUMN MST_HIMOKU.HIMOKU_NM IS '費目名';

COMMENT
	ON COLUMN MST_HIMOKU.HIMOKU_KBN IS '費目区分';

COMMENT
	ON COLUMN MST_HIMOKU.DEL_FLG IS '削除フラグ';

COMMENT
	ON COLUMN MST_HIMOKU.INS_USER IS '登録者';

COMMENT
	ON COLUMN MST_HIMOKU.INS_DATE IS '登録日';

COMMENT
	ON COLUMN MST_HIMOKU.UPD_USER IS '更新者';

COMMENT
	ON COLUMN MST_HIMOKU.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN MST_HIMOKU.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : MST_SETAI
CREATE TABLE MST_SETAI(
	SETAI_ID VARCHAR2(8) NOT NULL ENABLE
	, SETAI_NM NVARCHAR2(32) NOT NULL ENABLE
	, SETAI_NM_KANA NVARCHAR2(100)
	, POST_NO VARCHAR2(8)
	, ADDRESS NVARCHAR2(100)
	, TEL_NO VARCHAR2(13)
	, DEL_FLG VARCHAR2(1)
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1 NOT NULL ENABLE
	, CONSTRAINT MST_SETAI_PK PRIMARY KEY (SETAI_ID)
);

COMMENT
	ON TABLE MST_SETAI IS '世帯マスタ';

COMMENT
	ON COLUMN MST_SETAI.SETAI_ID IS '世帯ID';

COMMENT
	ON COLUMN MST_SETAI.SETAI_NM IS '世帯名';

COMMENT
	ON COLUMN MST_SETAI.SETAI_NM_KANA IS '世帯名カナ';

COMMENT
	ON COLUMN MST_SETAI.POST_NO IS '郵便番号';

COMMENT
	ON COLUMN MST_SETAI.ADDRESS IS '住所';

COMMENT
	ON COLUMN MST_SETAI.TEL_NO IS '電話番号';

COMMENT
	ON COLUMN MST_SETAI.DEL_FLG IS '削除フラグ';

COMMENT
	ON COLUMN MST_SETAI.INS_USER IS '登録者';

COMMENT
	ON COLUMN MST_SETAI.INS_DATE IS '登録日';

COMMENT
	ON COLUMN MST_SETAI.UPD_USER IS '更新者';

COMMENT
	ON COLUMN MST_SETAI.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN MST_SETAI.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : MST_KOJIN
CREATE TABLE MST_KOJIN(
	KOJIN_ID VARCHAR2(8) NOT NULL ENABLE
	, SETAI_ID VARCHAR2(8) NOT NULL ENABLE
	, PASS VARCHAR2(12) NOT NULL ENABLE
	, KOJIN_NM NVARCHAR2(32) NOT NULL ENABLE
	, KOJIN_NM_KANA NVARCHAR2(100)
	, SEIBETSU_KBN VARCHAR2(1)
	, ZOKUGARA VARCHAR2(2)
	, SETAINUSHI_FLG VARCHAR2(1)
	, DEL_FLG VARCHAR2(1)
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1 NOT NULL ENABLE
	, KOJIN_NICKNM VARCHAR2(32)
	, CONSTRAINT MST_KOJIN_PK PRIMARY KEY (KOJIN_ID)
	, CONSTRAINT MST_KOJIN_FK1 FOREIGN KEY (SETAI_ID) REFERENCES MST_SETAI(SETAI_ID) ENABLE
);

COMMENT
	ON TABLE MST_KOJIN IS '個人マスタ';

COMMENT
	ON COLUMN MST_KOJIN.KOJIN_ID IS '個人ID';

COMMENT
	ON COLUMN MST_KOJIN.SETAI_ID IS '世帯ID';

COMMENT
	ON COLUMN MST_KOJIN.PASS IS 'パスワード';

COMMENT
	ON COLUMN MST_KOJIN.KOJIN_NM IS '個人名';

COMMENT
	ON COLUMN MST_KOJIN.KOJIN_NM_KANA IS '個人名カナ';

COMMENT
	ON COLUMN MST_KOJIN.SEIBETSU_KBN IS '性別';

COMMENT
	ON COLUMN MST_KOJIN.ZOKUGARA IS '続柄';

COMMENT
	ON COLUMN MST_KOJIN.SETAINUSHI_FLG IS '世帯主フラグ';

COMMENT
	ON COLUMN MST_KOJIN.DEL_FLG IS '削除フラグ';

COMMENT
	ON COLUMN MST_KOJIN.INS_USER IS '登録者';

COMMENT
	ON COLUMN MST_KOJIN.INS_DATE IS '登録日';

COMMENT
	ON COLUMN MST_KOJIN.UPD_USER IS '更新者';

COMMENT
	ON COLUMN MST_KOJIN.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN MST_KOJIN.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : TRN_SHUSHI
CREATE TABLE TRN_SHUSHI(
	SHUSHI_ID VARCHAR2(8) NOT NULL ENABLE
	, KOJIN_ID VARCHAR2(8) NOT NULL ENABLE
	, YM VARCHAR2(6) NOT NULL ENABLE
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1 NOT NULL ENABLE
	, CONSTRAINT TRN_SHUSHI_PK PRIMARY KEY (SHUSHI_ID)
	, CONSTRAINT TRN_SHUSHI_FK1 FOREIGN KEY (KOJIN_ID) REFERENCES MST_KOJIN(KOJIN_ID) ENABLE
);

COMMENT
	ON TABLE TRN_SHUSHI IS '収支';

COMMENT
	ON COLUMN TRN_SHUSHI.SHUSHI_ID IS '収支ID';

COMMENT
	ON COLUMN TRN_SHUSHI.KOJIN_ID IS '個人ID';

COMMENT
	ON COLUMN TRN_SHUSHI.YM IS '年月';

COMMENT
	ON COLUMN TRN_SHUSHI.INS_USER IS '登録者';

COMMENT
	ON COLUMN TRN_SHUSHI.INS_DATE IS '登録日';

COMMENT
	ON COLUMN TRN_SHUSHI.UPD_USER IS '更新者';

COMMENT
	ON COLUMN TRN_SHUSHI.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN TRN_SHUSHI.REVISION IS 'リビジョン';

--------------------------------------------------------------------------------
-- Table : TRN_SHUSHI_DTL
CREATE TABLE TRN_SHUSHI_DTL(
	SHUSHI_ID VARCHAR2(8) NOT NULL ENABLE
	, SHUSHI_DTL_ID VARCHAR2(8) NOT NULL ENABLE
	, HIMOKU_CD VARCHAR2(2) NOT NULL ENABLE
	, KINGAKU NUMBER(9, 0) NOT NULL ENABLE
	, YMD DATE NOT NULL ENABLE
	, INS_USER VARCHAR2(32)
	, INS_DATE DATE DEFAULT SYSDATE
	, UPD_USER VARCHAR2(32)
	, UPD_DATE DATE
	, REVISION NUMBER(3, 0) DEFAULT 1 NOT NULL ENABLE
	, CONSTRAINT TRN_SHUSHI_DTL_PK PRIMARY KEY (SHUSHI_ID, SHUSHI_DTL_ID)
	, CONSTRAINT TRN_SHUSHI_DTL_FK1 FOREIGN KEY (SHUSHI_ID) REFERENCES TRN_SHUSHI(SHUSHI_ID) ENABLE
);

COMMENT
	ON TABLE TRN_SHUSHI_DTL IS '収支明細';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.SHUSHI_ID IS '収支ID';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.SHUSHI_DTL_ID IS '収支明細ID';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.HIMOKU_CD IS '費目CD';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.KINGAKU IS '金額';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.YMD IS '日付';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.INS_USER IS '登録者';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.INS_DATE IS '登録日';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.UPD_USER IS '更新者';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.UPD_DATE IS '更新日';

COMMENT
	ON COLUMN TRN_SHUSHI_DTL.REVISION IS 'リビジョン';

CREATE SEQUENCE SHUSHI_ID_SEQ;
